services:
  testapp:
    image: site:latest
    container_name: testapp
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8000
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_NAME: testdb
      DB_PORT: 5432
      DB_USER: test
      DB_PASS: P@ssw0rd

  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: P@ssw0rd

      volumes:
        - /root/testapp/db_data:/var/lib/mysql
